#!/usr/bin/env bash
#set-up nginx 

#command to install nginx
sudo apt-get update -y
sudo apt-get -y install nginx

#addibng the string to the default nginx file so when we curl the root we get the scring 
echo "Holberton School" > /var/www/html/index.nginx-debian.html

#restart server 
service nginx restart
