#!/usr/bin/env bash
# add the /redirect route

# Replace default Nginx config so /redirect_me returns 301
sudo sed -i 's@server_name _;@server_name _;\n\n    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }@' /etc/nginx/sites-available/default

service nginx restart
