#!/usr/bin/env bash

# Install Nginx
sudo apt-get update -y
sudo apt-get install -y nginx

# Add redirect_me location
sudo sed -i '/server_name _;/a \
    location /redirect_me {\n\
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\
    }' /etc/nginx/sites-available/default

# Create custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# Add custom 404 rule
sudo sed -i '/server_name _;/a \
    error_page 404 /404.html;\n\
    location = /404.html {\n\
        root /var/www/html;\n\
        internal;\n\
    }' /etc/nginx/sites-available/default

# Restart
sudo nginx -t && sudo systemctl restart nginx
